"""Stage 25 deterministic local-vision adapter primitives."""

from .benchmark import (
    GroundingScore,
    box_iou,
    point_distance,
    point_in_box,
    score_grounding,
)
from .mark_grid import (
    DEFAULT_CROP_SHORT_SIDE,
    DEFAULT_GRID_SIZE,
    Box,
    CropPlan,
    MarkGridError,
    Point,
    TwoPassMarkGridResult,
    box_center,
    box_from_extremity_cells,
    box_from_selected_cells,
    cell_bounds,
    cell_id_at_point,
    cell_row_col,
    map_box_from_crop,
    map_point_from_crop,
    normalize_box,
    normalize_point,
    plan_mark_grid_crop,
    plan_proportional_crop,
    two_pass_mark_grid_result,
)
from .provider import (
    LlamaCppLoopbackClient,
    VisionChatResult,
    VisionProviderError,
    build_direct_point_prompt,
    build_mark_grid_prompt,
    encode_image_data_uri,
    parse_direct_point_response,
    parse_mark_grid_response,
)

__all__ = [
    "DEFAULT_CROP_SHORT_SIDE",
    "DEFAULT_GRID_SIZE",
    "Box",
    "CropPlan",
    "GroundingScore",
    "LlamaCppLoopbackClient",
    "MarkGridError",
    "Point",
    "TwoPassMarkGridResult",
    "VisionChatResult",
    "VisionProviderError",
    "box_center",
    "box_from_extremity_cells",
    "box_from_selected_cells",
    "box_iou",
    "build_direct_point_prompt",
    "build_mark_grid_prompt",
    "cell_bounds",
    "cell_id_at_point",
    "cell_row_col",
    "encode_image_data_uri",
    "map_box_from_crop",
    "map_point_from_crop",
    "normalize_box",
    "normalize_point",
    "parse_direct_point_response",
    "parse_mark_grid_response",
    "plan_mark_grid_crop",
    "plan_proportional_crop",
    "point_distance",
    "point_in_box",
    "score_grounding",
    "two_pass_mark_grid_result",
]
