"""Stage 25 deterministic local-vision adapter primitives."""

from .mark_grid import (
    DEFAULT_CROP_SHORT_SIDE,
    DEFAULT_GRID_SIZE,
    Box,
    CropPlan,
    MarkGridError,
    Point,
    TwoPassMarkGridResult,
    box_center,
    box_from_extremity_cells,
    box_from_selected_cells,
    cell_bounds,
    cell_id_at_point,
    cell_row_col,
    map_box_from_crop,
    map_point_from_crop,
    normalize_box,
    normalize_point,
    plan_mark_grid_crop,
    plan_proportional_crop,
    two_pass_mark_grid_result,
)

__all__ = [
    "DEFAULT_CROP_SHORT_SIDE",
    "DEFAULT_GRID_SIZE",
    "Box",
    "CropPlan",
    "MarkGridError",
    "Point",
    "TwoPassMarkGridResult",
    "box_center",
    "box_from_extremity_cells",
    "box_from_selected_cells",
    "cell_bounds",
    "cell_id_at_point",
    "cell_row_col",
    "map_box_from_crop",
    "map_point_from_crop",
    "normalize_box",
    "normalize_point",
    "plan_mark_grid_crop",
    "plan_proportional_crop",
    "two_pass_mark_grid_result",
]
