from __future__ import annotations

import json
from pathlib import Path

from .binding import resolve_project
from .config import load_yaml_compatible
from .errors import ValidationError


def render_capability_audit(repo_root: Path, *, project_id: str | None) -> str:
    binding = resolve_project(repo_root, project_id)
    requirements = load_yaml_compatible(repo_root / "config" / "capability-requirements.yaml")
    profile_path = repo_root / "runtime" / "capability-profile.json"
    if not profile_path.exists():
        raise ValidationError("Runtime profile is missing; run the probe command first")
    try:
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValidationError("Runtime capability profile is corrupt") from exc
    if profile.get("project_id") != binding.project_id:
        raise ValidationError("Runtime profile belongs to another project")

    runtime_capabilities = profile.get("capabilities", {})
    rows = []
    for requirement in sorted(requirements.get("requirements", []), key=lambda item: item["capability"]):
        capability = requirement["capability"]
        runtime = runtime_capabilities.get(capability, {})
        paths = ", ".join(requirement.get("execution_paths", [])) or "—"
        rows.append(
            f"| `{capability}` | {str(requirement.get('required', False)).lower()} | "
            f"{requirement.get('required_quality', 'unspecified')} | "
            f"{runtime.get('status', 'unknown')} | "
            f"{runtime.get('execution_path', paths)} |"
        )

    verified_at = profile.get("verified_at", "unknown")
    body = "\n".join(rows) or "| — | — | — | unknown | — |"
    return f"""# ChatGPT Capabilities

> Generated audit view. Source of truth: `config/capability-requirements.yaml` for
> project needs and `runtime/capability-profile.json` for current local availability.
> Do not edit this file manually.

- Project: `{binding.project_id}`
- Surface: `{profile.get('surface', 'unknown')}`
- Runtime verified at: `{verified_at}`
- Hosted Chat/MCP status: `unknown` (not inferred from the local surface)

| Capability | Required | Required quality | Runtime status | Execution path |
|---|---:|---|---|---|
{body}
"""


def write_capability_audit(repo_root: Path, *, project_id: str | None) -> Path:
    output = repo_root / "project-context" / "CHATGPT_CAPABILITIES.md"
    output.write_text(render_capability_audit(repo_root, project_id=project_id), encoding="utf-8")
    return output

