use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::binding::resolve_project;
use crate::config::load_json_yaml;
use crate::error::{PlatformError, io_error};

pub fn write_capability_audit(
    repo_root: &Path,
    project_id: Option<&str>,
) -> Result<PathBuf, PlatformError> {
    let binding = resolve_project(repo_root, project_id)?;
    let requirements = load_json_yaml(&repo_root.join("config/capability-requirements.yaml"))?;
    let profile_path = repo_root.join("runtime/capability-profile.json");
    if !profile_path.exists() {
        return Err(PlatformError::Validation(
            "runtime profile is missing; run probe first".into(),
        ));
    }
    let profile = load_json_yaml(&profile_path)?;
    if profile.get("project_id").and_then(Value::as_str) != Some(&binding.project_id) {
        return Err(PlatformError::Validation(
            "runtime profile belongs to another project".into(),
        ));
    }
    let mut items = requirements
        .get("requirements")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    items.sort_by_key(|item| {
        item.get("capability")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_owned()
    });
    let rows: Vec<_> = items
        .iter()
        .map(|requirement| render_row(requirement, &profile))
        .collect();
    let body = if rows.is_empty() {
        "| — | false | unspecified | unknown | — |".into()
    } else {
        rows.join("\n")
    };
    let text = format!(
        "# ChatGPT Capabilities\n\n> Generated audit view. Source of truth: `config/capability-requirements.yaml` for\n> project needs and `runtime/capability-profile.json` for current local availability.\n> Do not edit this file manually.\n\n- Project: `{}`\n- Surface: `{}`\n- Runtime verified at: `{}`\n- Hosted Chat/MCP status: `unknown` (not inferred from the local surface)\n\n| Capability | Required | Required quality | Runtime status | Execution path |\n|---|---:|---|---|---|\n{}\n",
        binding.project_id,
        profile
            .get("surface")
            .and_then(Value::as_str)
            .unwrap_or("unknown"),
        profile
            .get("verified_at")
            .and_then(Value::as_str)
            .unwrap_or("unknown"),
        body
    );
    let output = repo_root.join("project-context/CHATGPT_CAPABILITIES.md");
    fs::write(&output, text).map_err(|error| io_error("cannot write capability audit", error))?;
    Ok(output)
}

fn render_row(requirement: &Value, profile: &Value) -> String {
    let capability = requirement
        .get("capability")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let runtime = profile
        .get("capabilities")
        .and_then(|value| value.get(capability));
    format!(
        "| `{capability}` | {} | {} | {} | {} |",
        requirement
            .get("required")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        requirement
            .get("required_quality")
            .and_then(Value::as_str)
            .unwrap_or("unspecified"),
        runtime
            .and_then(|value| value.get("status"))
            .and_then(Value::as_str)
            .unwrap_or("unknown"),
        runtime
            .and_then(|value| value.get("execution_path"))
            .and_then(Value::as_str)
            .unwrap_or("—")
    )
}
